### ISSUE TITLE
BUG: spectrocloud_cluster_profile_import resources is broken in version 0.21.0 and above

### ISSUE THREAD

**Issue by alexey-obrezkin-ah** [spectrocloud/terraform-provider-spectrocloud#547]
When using the `spectrocloud_cluster_profile_import` resource in Terraform provider version `0.21.0` and above, I am able to create a profile, but any subsequent `terraform apply` or `terraform plan` run fails with the following error:
```bash
Planning failed. Terraform encountered an error while generating this plan.
Error: import_file: '' expected type 'string', got unconvertible type 'models.V1ClusterProfile', value: '&{  0x14000118980 0x14000522a40 0x14000522ac0}'
```
This is most likely caused by the code that was released with version 0.21.0. In [resource_cluster_profile_import_feature.go](https://github.com/spectrocloud/terraform-provider-spectrocloud/blob/main/spectrocloud/resource_cluster_profile_import_feature.go) in the `resourceClusterProfileImportFeatureRead` function
```go
        clusterProfile, err := c.ClusterProfileExport(d.Id())
        ...
	if err := d.Set("import_file", clusterProfile); err != nil {
		return diag.FromErr(err)
	}
```

It tries to set `clusterProfile` of type `models.V1ClusterProfile` as the value for `import_file` property, but the type of `import_file` is `string`.
```go
		Schema: map[string]*schema.Schema{
			"import_file": {
				Type:     schema.TypeString,
				Required: true,
			},
                 ...
		},
```

**Comment by SivaanandM** [comment]
@alexey-obrezkin-ah 

The `spectrocloud_cluster_profile_import` resource is specifically used to import a JSON file into Palette. For instance, the import_file attribute is a file path. However, we do not maintain the state of the file content, meaning Day 2 operations on the cluster profile are not supported for updates for the file content.

I suggest an alternative approach:

Instead of exporting the cluster profile as JSON and importing it back into Palette, you can use `Terraform’s import `feature on the `spectrocloud_cluster_profile` resource to directly generate the Terraform configuration.

Example:

`import {
  to = spectrocloud_cluster_profile.cluster_profile
  id = "672c5ae21adfa1c28c9e37c9:project" # Example: "{cluster_profile_UID}:{context}"
}`

Run the following command to generate the configuration
`terraform plan -generate-config-out=cluster_profile.tf`

Import the state file using
`terraform import spectrocloud_cluster_profile.cluster-edge 672c5ae21adfa1c28c9e37c9:project`

**Comment by alexey-obrezkin-ah** [comment]
@SivaanandM 
I understand how `spectrocloud_cluster_profile_import` works, and it is perfectly fine for my use case (I don't need to update the JSON's content).
The problem is that when Terraform tries to read a profile that was imported earlier, it fails, regardless of whether the JSON was updated or not. The same problem occurs if I import a profile and then remove the `spectrocloud_cluster_profile_import` works resource from the Terraform code. When I try to run `terraform plan`, it should remove resource from spectrocloud and from the tf state (and it works before version 0.21.0), but it fails with the same error. 

The issue is clearly in this code: it tries to set models.V1ClusterProfile to a field that has a string type.
```go
        clusterProfile, err := c.ClusterProfileExport(d.Id())
        ...
	if err := d.Set("import_file", clusterProfile); err != nil {
		return diag.FromErr(err)
	}
```
and it should be something like 
```go
        importFilePath := d.Get("import_file").(string)
	if err := d.Set("import_file", importFilePath); err != nil {
		return diag.FromErr(err)
	}
```

The approach you proposed won't work or fit into our profiles development flow.

**Comment by SivaanandM** [comment]
@alexey-obrezkin-ah we have addressed this issue and released an patch version v0.21.7
 https://registry.terraform.io/providers/spectrocloud/spectrocloud/0.21.7

Kindly try now. 

Thank you

**Comment by alexey-obrezkin-ah** [comment]
@SivaanandM 
Thank you for the update; it works fine in version 0.21.7. 
However, the issue still persists in 0.22.0. Are you planning to release a patch for this version as well?

**Comment by SivaanandM** [comment]
Yes we already merged the change. Will be fixed in next release v0.22.1

**Comment by SivaanandM** [comment]
Issue is fixed on v0.21.7
